#!/usr/bin/env node

var fs = require('fs');
var path = require('path');

var packageDir = path.join(__dirname, '..', 'packages');

function rimraf(dir_path) {
  if (fs.existsSync(dir_path)) {
      fs.readdirSync(dir_path).forEach(function(entry) {
          var entry_path = path.join(dir_path, entry);
          if (fs.lstatSync(entry_path).isDirectory()) {
              rimraf(entry_path);
          } else {
              fs.unlinkSync(entry_path);
          }
      });
      fs.rmdirSync(dir_path);
  }
}

fs.readdir(packageDir, function(err, items) {
  for (var i=0; i<items.length; i++) {
      rimraf(path.join('node_modules', items[i]))
  }
});
