#!/usr/bin/env node

var fs = require('fs');
var path = require('path');
var exec = require('child_process').exec;

var packageDir = path.join(__dirname, '..', 'packages');

function rimraf(dir_path) {
  if (process.platform === "win32") {
    if (!fs.existsSync(dir_path)) {
      return;
    }

    exec(`rmdir /s /q ${dir_path}`, function(err, stdout, stderr) {
      if (err) {
        console.log(err);
      }
      console.log(stdout);
    });
  } else {
    exec(`rm -rf ${dir_path}`, function(err, stdout, stderr) {
      if (err) {
        console.log(err);
      }
      console.log(stdout);
    });
  }
}

fs.readdir(packageDir, function(err, items) {
  for (var i=0; i<items.length; i++) {
      rimraf(path.join('node_modules', items[i]))
  }
});
